config/routes.rb
Rails.application.routes.draw do

  resources :item_categories

  resources :reports do
    collection do
      get 'total_report'
      get 'date_range_report'
      get 'customer_report'
      get 'item_report'
      get 'search'
    end
  end

  resources :line_items

  resources :payments do
    collection do
      get 'make_payment'
    end
  end

  resources :configurations do 
    collection do 
      get 'update'
    end
  end

  resources :customers

  resources :items do
    get 'search'
    collection do
      get 'search'
    end
  end

resources :sales do
    collection do
      get 'update_line_item_options'
      get 'update_customer_options'
      get 'create_line_item'
      get 'update_totals'
      get 'add_item'
      get 'remove_item'
      get 'create_customer_association'
      get 'create_custom_item'
      get 'create_custom_customer'
      get 'add_comment'
      post 'override_price'
      post 'sale_discount'
    end
  end

  resources :dashboard do
    collection do
      get 'create_sale_with_product'
    end
  end

  devise_for :users
  resources :users do
    collection do
      post 'new_user'
    end
  end

  root 'dashboard#index'
end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
	has_many :items
	
	
	validates :name, :presence => {:message => "Nombre, No puede ir vacio"}
	validates_uniqueness_of :name, :scope => :user_id, :message => "Nombre, Está duplicado"


end

app/controllers/item_categories_controller.rb
class ItemCategoriesController < ApplicationController
  before_action :check_admin_user, only: [:edit, :create, :update, :destroy]
  before_action :set_item_category, only: [:show, :edit, :update, :destroy]

  # GET /item_categories
  # GET /item_categories.json
  def index
    @item_categories = ItemCategory.paginate(:page => params[:page], :per_page => 20).where(:user_id => current_user.user_id)
  end

  # GET /item_categories/1
  # GET /item_categories/1.json
  def show
  end

  # GET /item_categories/new
  def new
    @item_category = ItemCategory.new
  end

  # GET /item_categories/1/edit
  def edit
  end

  # POST /item_categories
  # POST /item_categories.json
  def create
    @item_category = ItemCategory.new(item_category_params)
    @item_category.user_id = current_user.user_id
      respond_to do |format|
        if @item_category.save
          format.html { redirect_to :back, notice: 'Se ha creado la categoria' }
          format.json { render action: 'show', status: :created, location: @item_category }    
        else
          format.html { render action: 'new' }
          format.json { render json: @item_category.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /item_categories/1
  # PATCH/PUT /item_categories/1.json
  def update
      respond_to do |format|
      if @item_category.update(item_category_params)
        format.html { redirect_to @item_category, notice: 'se ha actualizado la categoría' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_categories/1
  # DELETE /item_categories/1.json
  def destroy
    @item_category.destroy
    respond_to do |format|
      format.html { redirect_to item_categories_url }
      format.json { head :no_content }
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_category
      @item_category = ItemCategory.find(params[:id])

    end

    def check_admin_user
    unless current_user.is_admin || current_user.can_update_items
      flash[:alert] = "No tienes los permisos"
      redirect_to :back
    end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_category_params
      params.require(:item_category).permit(:name, :description)
    end

end

app/views/item_categories/_form.html.erb
<%= form_for(@item_category) do |f| %>
  <%= render :partial => 'template/form_errors', :object => @item_category %>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-sm-6">
        <div class="form-group">
          <label>Nombre</label>
          <%= f.text_field :name, :class => "form-control", :placeholder => "Nombre de la categoría" %>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="form-group">
          <label>Descripción</label>
          <%= f.text_area :description, :class => "form-control", :placeholder => "Descripción de la categoría" %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <%= f.submit 'Actualizar Categoria', :class => "btn btn-success btn-lg" %>
  </div>
</div>
<% end %>

app/views/item_categories/edit.html.erb
<%= render 'form' %>

app/views/item_categories/index.html.erb
<div class="panel panel-default">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
          
            <th>Nombre</th><!-- Name: -->
+            <th>Descripción</th><!-- Descripcion: -->
          </tr>
        </thead>

        <tbody>
          <% @item_categories.each do |item_category| %>
            <tr>
              <td><%= item_category.name %></td>
              <td><%= item_category.description %></td>
              <td><%= link_to 'Editar', edit_item_category_path(item_category) %> | <%= link_to 'Eliminar', item_category, method: :delete, data: { confirm: '¿Esta seguro que desea eliminarlo?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="panel-body">
        <%= will_paginate @item_categories, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

    <div class="col-sm-12">
      
      <%= link_to 'Nueva Categoria', new_item_category_path, :class => "btn btn-success btn-lg active" %><!-- New Item Category: -->
     
    </div>

app/views/item_categories/new.html.erb
<%= render 'form' %>

app/views/item_categories/show.html.erb
<%= render 'form' %>