config/routes.rb
Rails.application.routes.draw do

  resources :item_categories

  resources :reports do
    collection do
      get 'total_report'
      get 'date_range_report'
      get 'customer_report'
      get 'item_report'
      get 'search'
    end
  end

  resources :line_items

  resources :payments do
    collection do
      get 'make_payment'
    end
  end

  resources :configurations do 
    collection do 
      get 'update'
    end
  end

  resources :customers

  resources :items do
    get 'search'
    collection do
      get 'search'
    end
  end

resources :sales do
    collection do
      get 'update_line_item_options'
      get 'update_customer_options'
      get 'create_line_item'
      get 'update_totals'
      get 'add_item'
      get 'remove_item'
      get 'create_customer_association'
      get 'create_custom_item'
      get 'create_custom_customer'
      get 'add_comment'
      post 'override_price'
      post 'sale_discount'
    end
  end

  resources :dashboard do
    collection do
      get 'create_sale_with_product'
    end
  end

  devise_for :users
  resources :users do
    collection do
      post 'new_user'
    end
  end

  root 'dashboard#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @recent_sales = Sale.where(:user_id => current_user.user_id).order(:id).limit(10)
  	@popular_items = Item.where(:user_id => current_user.user_id).order(:id).limit(10)
  end

  def create_sale_with_product
		@sale = Sale.create
    @sale_by_vet = Sale.where(:user_id=>current_user.user_id).last
		item = Item.find(params[:item_id])
		LineItem.create(:item_id => params[:item_id].to_i, :quantity => params[:quantity].to_i, :price => item.price, :total_price => item.price * params[:quantity].to_i, :sale_id => @sale.id)
    
		price = (item.price * params[:quantity].to_i )

    @sale.tax = price * get_tax_rate
    @sale.amount = price
    @sale.total_amount = price + (price * get_tax_rate)
    @sale.user_id = current_user.user_id
    @sale.sale_by_vet = @sale_by_vet.sale_by_vet += 1 
    @sale.save

    redirect_to :controller => 'sales', :action => 'edit', :id => @sale.id
  end

	def get_tax_rate
    if @configurations.tax_rate.blank?
      return 0.00
    else
      return @configurations.tax_rate.to_f * 0.01
    end
  end
end

app/views/dashboard/_guest.html.erb
<div class="container">
  
  <%= form_for("user", :url => user_session_path, :html => { :class => "form-signin" }) do |f| %>
  <h2 class="form-signin-heading"><a target="_blank" href="http://www.gikma.com">Gikma.com</a></h2><!-- PushVendor.com -->
  	
      <%= f.text_field :email, :class => 'form-control', :placeholder => 'Email Address' %>
      <%= f.password_field :password, :class => 'form-control', :placeholder => 'Password' %>
      <label class="checkbox">
      	<%= f.check_box :remember_me %> Remember me
      </label>
      
      <%= link_to "Olvidaste tu contraseña?", new_password_path('user') %><!-- Forgot your password? -->
      <button class="btn btn-lg btn-primary btn-block" value="Sign in" type="submit">Acceder</button>
      
    <p class="copyright">Copyright &copy; 2015 Gikma</p><!-- 2014 PushVendor -->
    <% end %>

</div>

app/views/dashboard/_logged_in.html.erb
<%= render :partial => 'template/dashboard_menu' %>

<div class="panel panel-default">
  <div class="panel-heading">Ventas Recientes</div>
  <div class="table-responsive">
	  <table class="table table-striped table-bordered table-hover">
	  	<tr>
	  		<th>#</th>
<th>Creado</th><!-- Created-->
      <th>Cliente</th><!-- Customer -->
        <th>Total</th><!-- Total-->
        <th>Impuesto</th><!-- Tax-->
        <th>Pagado</th><!-- Paid-->
        <th>Balance</th><!-- Balance-->
        <th></th>
	  	</tr>
	  	<% for sale in @recent_sales %>
	    	<tr class="<%= sale.remaining_balance == 0.00 && !sale.total_amount.blank? ? 'success' : '' %>">
	    		<td><%= sale.sale_by_vet %></td>
          <td><%= sale.created_at.strftime("%m/%d/%y %I:%M:%S %p")  %></td>
          <td><%= sale.customer.blank? ? '-' : sale.customer.last_name %></td>
          <td><%= number_to_currency sale.total_amount %></td>
          <td><%= number_to_currency sale.tax %></td>
          <td><%= number_to_currency sale.paid_total %></td>
          <td><%= sale.remaining_balance == 0.00 && sale.payments.count > 0 ? "Pagado" : "#{number_to_currency sale.remaining_balance}" %></td>
          <td><%= link_to 'Mostrar', edit_sale_path(sale) %> | <%= link_to 'Eliminar', sale, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
	    	</tr>
	    <% end %>
	  </table>
	</div>
</div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  
  <div class="panel-heading">Articulos Populares</div><!-- Popular Items-->

  <div class="panel-body">
    <% for item in @popular_items %>
      <%= link_to create_sale_with_product_dashboard_index_path(:item_id => item.id, :quantity => 1) do %>
        <button type="button" class="btn btn-default">
          <%= item.name %>
        </button>
      <% end %>
    <% end %>
  </div>

</div>


<div class="panel panel-default">
  <!-- Default panel contents -->
  
  <div class="panel-heading">Resumen</div><!-- Summary-->

  <!-- Table -->
  <%= render :partial => 'template/sales_summary' %>
</div>

app/views/dashboard/index.html.erb
<% if user_signed_in? %>
	<%= render :partial => 'logged_in' %>
<% else %>
	<%= render :partial => 'guest' %>
<% end %>