config/routes.rb
Rails.application.routes.draw do

  resources :item_categories

  resources :reports do
    collection do
      get 'total_report'
      get 'date_range_report'
      get 'customer_report'
      get 'item_report'
      get 'search'
    end
  end

  resources :line_items

  resources :payments do
    collection do
      get 'make_payment'
    end
  end

  resources :configurations do 
    collection do 
      get 'update'
    end
  end

  resources :customers

  resources :items do
    get 'search'
    collection do
      get 'search'
    end
  end

resources :sales do
    collection do
      get 'update_line_item_options'
      get 'update_customer_options'
      get 'create_line_item'
      get 'update_totals'
      get 'add_item'
      get 'remove_item'
      get 'create_customer_association'
      get 'create_custom_item'
      get 'create_custom_customer'
      get 'add_comment'
      post 'override_price'
      post 'sale_discount'
    end
  end

  resources :dashboard do
    collection do
      get 'create_sale_with_product'
    end
  end

  devise_for :users
  resources :users do
    collection do
      post 'new_user'
    end
  end

  root 'dashboard#index'
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :customer
	belongs_to :user
	has_many :line_items, dependent: :destroy
	has_many :items, :through => :line_items
	has_many :connections, :through => :customer
	has_many :payments, dependent: :destroy

	accepts_nested_attributes_for :line_items, :allow_destroy => true
	accepts_nested_attributes_for :items, :allow_destroy => true
	accepts_nested_attributes_for :payments, :allow_destroy => true



	def remaining_balance
		if self.total_amount.blank?
			balance = 0.00
		else
			balance = self.total_amount - paid_total
		end

		if balance < 0
			return 0
		else
			return balance.round(2)
		end
	end

	def get_discounted_amount
		self.total_amount * self.discount
	end

	def paid_total
		paid_total = 0.00
		unless self.payments.blank?
			for payment in self.payments
				paid_total += payment.amount.blank? ? 0.00 : payment.amount
			end
		end
		return paid_total
	end

	def change_due
		if self.total_amount.blank?
			return 0.00
		else
			if paid_total > self.total_amount
				return paid_total - self.total_amount
			else
				return 0.00
			end
		end
	end

	def add_customer(customer_id)
		self.customer_id = customer_id
    self.save
	end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_configurations

  def index
    @sales = Sale.order('id ASC').where(:user_id => current_user.user_id).paginate(:page => params[:page], :per_page => 20)
  end
def show
redirect_to :back
end

  def new
    @sale_by_vet = Sale.where(:user_id=>current_user.user_id).last
    if @sale_by_vet.nil?
      @sale = Sale.create(:user_id=> current_user.user_id,:sale_by_vet => 1)
      redirect_to :controller => 'sales', :action => 'edit', :id => @sale.id
    else
      sale_by_vet = @sale_by_vet.sale_by_vet += 1 
      @sale = Sale.create(:user_id => current_user.user_id,:sale_by_vet => sale_by_vet)
      redirect_to :controller => 'sales', :action => 'edit', :id => @sale.id

    end
  end

  def edit
    user_id = Sale.find(params[:id])
    if user_id.user_id == current_user.user_id
      set_sale
    
      populate_items
      populate_customers

      @sale.line_items.build
      @sale.payments.build

      @custom_item = Item.new
      @custom_customer = Customer.new
    else
      redirect_to root_path, :alert => "Error, Venta no encontrada."
    end

  end

  def destroy
    set_sale

    if current_user.can_remove_sales == true
      @sale.destroy
      respond_to do |format|
      format.html { redirect_to sales_url, notice: 'La venta ha sido eliminada'}
      format.json { head :no_content }
    end
    else
      redirect_to @sale, alert: 'No tiene los permisos para eliminar'
    end
    
  end

  # searched Items
  def update_line_item_options
    set_sale
    populate_items

    if params[:search][:item_category].blank?
      @available_items = Item.where('name ILIKE ? AND published = true OR description ILIKE ? AND published = true OR sku ILIKE ? AND published = true', "%#{params[:search][:item_name]}%", "%#{params[:search][:item_name]}%", "%#{params[:search][:item_name]}%").where(:user_id => current_user.user_id).limit(5)
    elsif params[:search][:item_name].blank?
      @available_items = Item.where(:item_category_id => params[:search][:item_category]).where(:user_id => current_user.user_id).limit(5)
    else
      @available_items = Item.where('name ILIKE ? AND published = true AND item_category_id = ? OR description ILIKE ? AND published = true AND item_category_id = ? OR sku ILIKE ? AND published = true AND item_category_id = ?', "%#{params[:search][:item_name]}%", "#{params[:search][:item_category]}", "%#{params[:search][:item_name]}%", "#{params[:search][:item_category]}", "%#{params[:search][:item_name]}%", "#{params[:search][:item_category]}",).where(:user_id => current_user.user_id).limit(5)
    end

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  def update_customer_options
    set_sale
    populate_items
    @available_customers = Customer.where('last_name ILIKE ? AND published = true OR first_name ILIKE ? AND published = true OR email_address ILIKE ? AND published = true OR phone_number ILIKE ? AND published = true', "%#{params[:search][:customer_name]}%","%#{params[:search][:customer_name]}%", "%#{params[:search][:customer_name]}%", "%#{params[:search][:customer_name]}%").where(:user_id => current_user.user_id).limit(5)
    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  def create_customer_association
    set_sale

    unless @sale.blank? || params[:customer_id].blank?
      @sale.customer_id = params[:customer_id]
      @sale.save
    end


    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  # Add a searched Item
  def create_line_item
    set_sale
    populate_items

    existing_line_item = LineItem.where("item_id = ? AND sale_id = ?", params[:item_id], @sale.id).first
    
    if existing_line_item.blank?
      line_item = LineItem.new(:item_id => params[:item_id], :sale_id => params[:sale_id], :quantity => params[:quantity])
      line_item.price = line_item.item.price
      line_item.save

      remove_item_from_stock(params[:item_id], 1)
      update_line_item_totals(line_item)
    else
      existing_line_item.quantity += 1
      existing_line_item.save

      remove_item_from_stock(params[:item_id], 1)
      update_line_item_totals(existing_line_item)
    end

    update_totals

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end


  # Remove Item
  def remove_item
    set_sale
    populate_items

    line_item = LineItem.where(:sale_id => params[:sale_id], :item_id => params[:item_id]).first
    line_item.quantity -= 1
    if line_item.quantity <= 0
      line_item.destroy
    else
      line_item.save
      update_line_item_totals(line_item)
    end

    return_item_to_stock(params[:item_id], 1)

    update_totals

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  # Add one Item
  def add_item
    set_sale
    populate_items

    line_item = LineItem.where(:sale_id => params[:sale_id], :item_id => params[:item_id]).first
    line_item.quantity += 1
    line_item.save

    remove_item_from_stock(params[:item_id], 1)
    update_line_item_totals(line_item)

    update_totals

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  def create_custom_item
    set_sale
    populate_items

    custom_item = Item.new
    custom_item.sku = "CI#{(rand(5..30) + rand(5..30)) * 11}_#{(rand(5..30) + rand(5..30)) * 11}"
    custom_item.name = params[:custom_item][:name]
    custom_item.description = params[:custom_item][:description]
    custom_item.price = params[:custom_item][:price]
    custom_item.stock_amount = params[:custom_item][:stock_amount]
    custom_item.item_category_id = params[:custom_item][:item_category_id]
    custom_item.user_id = current_user.user

    custom_item.save

    custom_line_item = LineItem.new(:item_id => custom_item.id, :sale_id => @sale.id, :quantity => custom_item.stock_amount, :price => custom_item.price )
    custom_line_item.total_price = custom_item.price * custom_item.stock_amount
    custom_line_item.save

    update_totals

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  def create_custom_customer
    set_sale
    populate_items

    custom_customer = Customer.new
    custom_customer.first_name = params[:custom_customer][:first_name]
    custom_customer.last_name = params[:custom_customer][:last_name]
    custom_customer.email_address = params[:custom_customer][:email_address]
    custom_customer.phone_number = params[:custom_customer][:phone_number]
    custom_customer.address = params[:custom_customer][:address]
    custom_customer.city = params[:custom_customer][:city]
    custom_customer.state = params[:custom_customer][:state]
    custom_customer.zip = params[:custom_customer][:zip]
    custom_customer.user_id = current_user.user_id
    custom_customer.save

    @sale.add_customer(custom_customer.id)

    update_totals

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end


  # update Total For Line Items
  def update_line_item_totals(line_item)
    line_item.total_price = line_item.price * line_item.quantity
    line_item.save
  end


  def override_price
    @sale = Sale.find(params[:override_price][:sale_id])
    item = Item.where(:sku => params[:override_price][:line_item_sku] ).first
    line_item = LineItem.where(:sale_id => params[:override_price][:sale_id], :item_id => item.id).first
    line_item.price = params[:override_price][:price].gsub('$', '')
    line_item.save

    update_line_item_totals(line_item)
    update_totals

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  def sale_discount
    @sale = Sale.find_by_sale_by_vet(params[:sale_discount][:sale_id])

    @sale.discount = params[:sale_discount][:discount]
    @sale.save

    update_totals

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  # Destroy Line Item
  def destroy_line_item
    set_sale
    update_totals

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  # Update Sale Totals
  def update_totals

    tax_amount = get_tax_rate

    set_sale

    @sale.amount = 0.00

    for line_item in @sale.line_items
      @sale.amount += line_item.total_price
    end

    @sale.tax = @sale.amount * tax_amount
    total_amount = @sale.amount + (@sale.amount * tax_amount)

    if @sale.discount.blank?
      @sale.total_amount = total_amount
    else
      discount_amount = total_amount * @sale.discount
      @sale.total_amount = total_amount - discount_amount
    end
    @sale.user_id = current_user.user_id
    @sale.save
  end

  def add_comment
    set_sale
    @sale.comments = params[:sale_comments][:comments]
    sale.user_id = current_user.user_id
    @sale.save

    respond_to do |format|
      format.js { ajax_refresh }
    end
  end

  private

    def ajax_refresh
      return render(:file => 'sales/ajax_reload.js.erb')
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      if @sale.blank?
        if params[:sale_id].blank?
          if params[:search].blank?
            @sale = Sale.find(params[:id])
          else
            @sale = Sale.find(params[:search][:sale_id])
          end
        else 
          @sale = Sale.find(params[:sale_id])
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:amount, :tax, :discount, :total_amount, :tax_paid, :amount_paid, :paid, :payment_type_id, :customer_id, :comments, :line_items_attributes, :items_attributes)
    end

    def populate_items
      @available_items = Item.where(:published => true, :user_id => current_user.user_id).limit(5)
    end

    def populate_customers
      @available_customers = Customer.where(:published => true, :user_id => current_user.user_id).limit(5)
    end

    def remove_item_from_stock(item_id, quantity)
      item = Item.find(item_id)
      item.stock_amount = item.stock_amount - quantity

app/views/sales/ajax_reload.js.erb
// Shared options
$('.added_items').html("<%= escape_javascript render(:file => 'sales/shared/_added_items.html.erb') %>");
$('.sale_totals').html("<%= escape_javascript render(:file => 'sales/shared/_sale_totals.html.erb') %>");
$('.sale_payments').html("<%= escape_javascript render(:file => 'sales/shared/_sale_payments.html.erb') %>");
$('.added_customer').html("<%= escape_javascript render(:file => 'sales/shared/_added_customer.html.erb') %>");
$('#makePayment .modal-body').html("<%= escape_javascript render(:file => 'sales/shared/_payment.html.erb') %>");
$('#customItem .modal-body').html("<%= escape_javascript render(:file => 'sales/shared/_create_custom_item.html.erb') %>");
$('#customCustomer .modal-body').html("<%= escape_javascript render(:file => 'sales/shared/_create_custom_customer.html.erb') %>");

$('.print_totals').html("<%= escape_javascript render(:file => 'sales/shared/_invoice_totals.html.erb') %>");
$('.searched_items').html("<%= escape_javascript render(:file => 'sales/shared/_searched_items.html.erb') %>");

$('.searched_customers').html("<%= escape_javascript render(:file => 'sales/shared/_searched_customers.html.erb') %>");


$('.edit_sale').show();

app/views/sales/edit.html.erb
<div class="sale_form_details">
	<%= render 'sales/shared/form' %>
</div>

app/views/sales/index.html.erb
<div class="panel panel-default">
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>#</th>
        <th>Creado</th><!-- Created -->
         <th>Cliente</th><!-- Customer -->
          <th>Total</th><!-- Total -->
          <th>Impuesto</th><!-- Tax -->
          <th>Pagado</th><!-- Paid -->
          <th>Balance</th><!-- Balance -->
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @sales.each do |sale| %>
          <tr class="<%= sale.remaining_balance == 0.00 && !sale.total_amount.blank? ? 'success' : '' %>">
            <td><%= sale.sale_by_vet %></td>
            <td><%= sale.created_at.strftime("%m/%d/%y %I:%M:%S %p")  %></td>
            <td><%= sale.customer.blank? ? '-' : sale.customer.last_name %></td>
            <td><%= number_to_currency sale.total_amount %></td>
            <td><%= number_to_currency sale.tax %></td>
            <td><%= number_to_currency sale.paid_total %></td>
            <td><%= sale.remaining_balance == 0.00 && sale.payments.count > 0 ? "Pagado" : "#{number_to_currency sale.remaining_balance}" %></td>
            <td><%= link_to 'Mostrar', edit_sale_path(sale) %> | <%= link_to 'Eliminar', sale, method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="panel-body">
        <%= will_paginate @sales, renderer: BootstrapPagination::Rails %>
      </div>
  </div>
</div>

<div class="panel panel-default">
  <!-- Default panel contents -->
  
  <div class="panel-heading">Resumen</div><!-- Summary -->

  <!-- Table -->
  <%= render :partial => 'template/sales_summary' %>
</div>

<br>


<%= link_to 'Nueva Venta', new_sale_path, :class => "btn btn-success btn-lg active" %>

app/views/sales/new.html.erb
<div class="sale_form_details">
	<%= render 'form' %>
</div>